### ISSUE TITLE
[Stats] "Something went wrong try reloading the page"

### ISSUE THREAD

**Issue by TecEash1** [harbassan/spicetify-apps#121]
After updating to the latest version of stats and enabling "use lastfm for stats" and trying to filter my stats for past week I am met with this error every time I load up stats. 

Not sure if this is relevant/helpful but just to let you know I also got a message after updating saying that I am still on an outdated version for some reason.

**Comment by harbassan** [comment]
Could you open the console and check for any errors due to stats.

**Comment by SecretUnicorn** [comment]
I face the same issue and the following error gets printed into console when I click on Statistics:

```
vendor~xpui.js:29 TypeError: Cannot read properties of undefined (reading 'map')
    at ArtistsPage (spicetify-routes-stats.js:6464:36)
    at aa (vendor~xpui.js:29:2275298)
    at ja (vendor~xpui.js:29:2284816)
    at Va (vendor~xpui.js:29:2284150)
    at Ba (vendor~xpui.js:29:2283808)
    at zs (vendor~xpui.js:29:2330655)
    at kc (vendor~xpui.js:29:2314701)
    at Pc (vendor~xpui.js:29:2314629)
    at Cc (vendor~xpui.js:29:2314492)
    at yc (vendor~xpui.js:29:2311479)
xpui.js:1 TypeError: Cannot read properties of undefined (reading 'map')
    at ArtistsPage (spicetify-routes-stats.js:6464:36)
    at aa (vendor~xpui.js:29:2275298)
    at ja (vendor~xpui.js:29:2284816)
    at Va (vendor~xpui.js:29:2284150)
    at Ba (vendor~xpui.js:29:2283808)
    at zs (vendor~xpui.js:29:2330655)
    at kc (vendor~xpui.js:29:2314701)
    at Pc (vendor~xpui.js:29:2314629)
    at Cc (vendor~xpui.js:29:2314492)
    at yc (vendor~xpui.js:29:2311479)
    ```

**Comment by TecEash1** [comment]
Sorry for the late reply, this is what my console says:

```CONSOLE
spicetify-routes-stats.js:6142 stats - lfmTopTracks fetch time: 356.6000000014901
vendor~xpui.js:1 TypeError: Cannot read properties of undefined (reading 'playcount')
    at TracksPage (spicetify-routes-stats.js:7062:39)
    at _a (vendor~xpui.js:1:2196221)
    at Os (vendor~xpui.js:1:2210312)
    at Ts (vendor~xpui.js:1:2209520)
    at Tc (vendor~xpui.js:1:2258902)
    at vl (vendor~xpui.js:1:2244688)
    at gl (vendor~xpui.js:1:2244616)
    at _l (vendor~xpui.js:1:2244479)
    at rl (vendor~xpui.js:1:2241286)
    at cl (vendor~xpui.js:1:2241675)
ds @ vendor~xpui.js:1
xpui.js:1 TypeError: Cannot read properties of undefined (reading 'playcount')
    at TracksPage (spicetify-routes-stats.js:7062:39)
    at _a (vendor~xpui.js:1:2196221)
    at Os (vendor~xpui.js:1:2210312)
    at Ts (vendor~xpui.js:1:2209520)
    at Tc (vendor~xpui.js:1:2258902)
    at vl (vendor~xpui.js:1:2244688)
    at gl (vendor~xpui.js:1:2244616)
    at _l (vendor~xpui.js:1:2244479)
    at rl (vendor~xpui.js:1:2241286)
    at cl (vendor~xpui.js:1:2241675)
l @ xpui.js:1
```

**Comment by harbassan** [comment]
try out the latest version and let me know what it says

**Comment by TecEash1** [comment]
Yup! It seems to work perfectly now!
