### ISSUE TITLE
[Library] Crash on startup

### ISSUE THREAD

**Issue by zszechuan** [harbassan/spicetify-apps#163]
Hi, whenever i try to open the Library app i'm met with an all-too-familiar crash screen:

![immagine](https://github.com/user-attachments/assets/2df0902c-fd04-4cf5-8363-2510bd0c525f)

I have the latest version of Spotify, Spicetify and Library, i have tried uninstalling and reinstalling all three but nothing has changed
Here's the dev console log:

```
TypeError: Cannot read properties of undefined (reading 'name')
    at spicetify-routes-library.js:989:36
    at Array.map (<anonymous>)
    at AlbumsPage (spicetify-routes-library.js:983:31)
    at pa (vendor~xpui.js:1:2099506)
    at bs (vendor~xpui.js:1:2113597)
    at vc (vendor~xpui.js:1:2159688)
    at ml (vendor~xpui.js:1:2147973)
    at hl (vendor~xpui.js:1:2147901)
    at pl (vendor~xpui.js:1:2147764)
    at tl (vendor~xpui.js:1:2144571)Caused by: React ErrorBoundary TypeError: Cannot read properties of undefined (reading 'name')
    at AlbumsPage (https://xpui.app.spotify.com/spicetify-routes-library.js:925:23)
    at NavbarContainer (https://xpui.app.spotify.com/spicetify-routes-library.js:1536:28)
    at div
    at App (https://xpui.app.spotify.com/spicetify-routes-library.js:1577:56)
    at render
    at C (https://xpui.app.spotify.com/vendor~xpui.js:1:2280889)
    at B (https://xpui.app.spotify.com/vendor~xpui.js:1:2284566)
    at Sh (https://xpui.app.spotify.com/xpui.js:1:651235)
    at Suspense
    at p (https://xpui.app.spotify.com/vendor~xpui.js:1:3137692)
    at Suspense
    at l (https://xpui.app.spotify.com/xpui.js:1:212238)
    at c (https://xpui.app.spotify.com/xpui.js:1:212313)
    at main
    at https://xpui.app.spotify.com/xpui.js:1:556519
    at div
    at div
    at https://xpui.app.spotify.com/xpui.js:1:240762
    at div
    at div
    at tn (https://xpui.app.spotify.com/xpui.js:1:559729)
    at div
    at Fi (https://xpui.app.spotify.com/xpui.js:1:557760)
    at div
    at wu (https://xpui.app.spotify.com/xpui.js:1:619994)
    at o (https://xpui.app.spotify.com/xpui.js:1:526073)
    at Jn (https://xpui.app.spotify.com/xpui.js:1:568105)
    at m (https://xpui.app.spotify.com/xpui.js:1:521434)
    at zi (https://xpui.app.spotify.com/xpui.js:1:558675)
    at c (https://xpui.app.spotify.com/xpui.js:1:743965)
    at t (https://xpui.app.spotify.com/vendor~xpui.js:1:1886445)
    at A (https://xpui.app.spotify.com/xpui.js:1:448595)
    at Suspense
    at Jc
    at a (https://xpui.app.spotify.com/xpui.js:1:714011)
    at a (https://xpui.app.spotify.com/xpui.js:1:253665)
    at c (https://xpui.app.spotify.com/xpui.js:1:412180)
    at l (https://xpui.app.spotify.com/xpui.js:1:443737)
    at a (https://xpui.app.spotify.com/xpui.js:1:217659)
    at r (https://xpui.app.spotify.com/vendor~xpui.js:1:3236434)
    at Nc (https://xpui.app.spotify.com/xpui.js:1:615315)
    at d (https://xpui.app.spotify.com/xpui.js:1:423569)
    at c (https://xpui.app.spotify.com/vendor~xpui.js:1:3286568)
    at Suspense
    at kt (https://xpui.app.spotify.com/xpui.js:1:550738)
    at a (https://xpui.app.spotify.com/xpui.js:1:254129)
    at a (https://xpui.app.spotify.com/xpui.js:1:270286)
    at ei (https://xpui.app.spotify.com/xpui.js:1:555194)
    at He (https://xpui.app.spotify.com/xpui.js:1:546793)
    at bd (https://xpui.app.spotify.com/xpui.js:1:625401)
    at kd (https://xpui.app.spotify.com/xpui.js:1:632029)
    at https://xpui.app.spotify.com/xpui.js:1:662520
    at _ (https://xpui.app.spotify.com/xpui.js:1:451655)
    at p (https://xpui.app.spotify.com/xpui.js:1:742132)
    at p (https://xpui.app.spotify.com/xpui.js:1:456378)
    at l (https://xpui.app.spotify.com/xpui.js:1:744857)
    at c (https://xpui.app.spotify.com/xpui.js:1:197587)
    at d (https://xpui.app.spotify.com/xpui.js:1:117711)
    at c (https://xpui.app.spotify.com/xpui.js:1:428277)
    at u (https://xpui.app.spotify.com/xpui.js:1:244942)
    at h (https://xpui.app.spotify.com/xpui.js:1:222986)
    at d (https://xpui.app.spotify.com/xpui.js:1:712028)
    at s (https://xpui.app.spotify.com/vendor~xpui.js:1:3200439)
    at Spicetify.ReactComponent.PlatformProvider (https://xpui.app.spotify.com/xpui.js:1:549418)
    at e (https://xpui.app.spotify.com/vendor~xpui.js:1:2199277)
    at c (https://xpui.app.spotify.com/xpui.js:1:428836)
    at c (https://xpui.app.spotify.com/xpui.js:1:716706)
    at le (https://xpui.app.spotify.com/vendor~xpui.js:1:2906882)
    at c (https://xpui.app.spotify.com/xpui.js:1:738278)
    at He (https://xpui.app.spotify.com/xpui.js:1:546793)
    at o (https://xpui.app.spotify.com/xpui.js:1:411523)
    at s (https://xpui.app.spotify.com/vendor~xpui.js:1:3670822)
    at it (https://xpui.app.spotify.com/xpui.js:1:547460)
    at Qe (https://xpui.app.spotify.com/xpui.js:1:547326)
    at Ye (https://xpui.app.spotify.com/xpui.js:1:547121)
    at We (https://xpui.app.spotify.com/xpui.js:1:547023)
    at a (https://xpui.app.spotify.com/xpui.js:1:738774)
    at a (https://xpui.app.spotify.com/xpui.js:1:446400)
    at g (https://xpui.app.spotify.com/xpui.js:1:424328)
    at a (https://xpui.app.spotify.com/xpui.js:1:713059)
    at a (https://xpui.app.spotify.com/xpui.js:1:712613)
    at a (https://xpui.app.spotify.com/xpui.js:1:745125)
    at a (https://xpui.app.spotify.com/xpui.js:1:744251)
    at a (https://xpui.app.spotify.com/xpui.js:1:743610)
    at Re (https://xpui.app.spotify.com/xpui.js:1:546316)
    at c (https://xpui.app.spotify.com/vendor~xpui.js:1:1364611)
    at u (https://xpui.app.spotify.com/xpui.js:1:714585)
    at a (https://xpui.app.spotify.com/xpui.js:1:714354)
    at $e (https://xpui.app.spotify.com/xpui.js:1:547218)
    at a (https://xpui.app.spotify.com/xpui.js:1:940476)
    at nt (https://xpui.app.spotify.com/xpui.js:1:547536)
    at He (https://xpui.app.spotify.com/xpui.js:1:546793)
    at Spicetify.ReactComponent.PlatformProvider (https://xpui.app.spotify.com/xpui.js:1:547655)
    at Oh (https://xpui.app.spotify.com/xpui.js:1:663092)
    at W (https://xpui.app.spotify.com/vendor~xpui.js:1:2270611)
    at p (https://xpui.app.spotify.com/vendor~xpui.js:1:3137692)
    at Suspense
    at l (https://xpui.app.spotify.com/xpui.js:1:212238)
    at c (https://xpui.app.spotify.com/xpui.js:1:212313)
    at V (https://xpui.app.spotify.com/vendor~xpui.js:1:2283931)
    at ct (https://xpui.app.spotify.com/xpui.js:1:548773)
    at Rh (https://xpui.app.spotify.com/xpui.js:1:663257)
    at p (https://xpui.app.spotify.com/vendor~xpui.js:1:3137692)
    at Suspense
    at l (https://xpui.app.spotify.com/xpui.js:1:212238)
    at c (https://xpui.app.spotify.com/xpui.js:1:212313)
    at c (https://xpui.app.spotify.com/vendor~xpui.js:1:1364611)
l @ xpui.js:1
(anonymous) @ xpui.js:1
withScope @ vendor~xpui.js:1
l @ vendor~xpui.js:1
u @ vendor~xpui.js:1
c @ xpui.js:1
(anonymous) @ xpui.js:1
withScope @ vendor~xpui.js:1
l @ vendor~xpui.js:1
u @ vendor~xpui.js:1
u @ xpui.js:1
onError @ xpui.js:1
(anonymous) @ vendor~xpui.js:1
withScope @ vendor~xpui.js:1
l @ vendor~xpui.js:1
u @ vendor~xpui.js:1
componentDidCatch @ vendor~xpui.js:1
r.componentDidCatch.n.callback @ vendor~xpui.js:1
Fr @ vendor~xpui.js:1
gc @ vendor~xpui.js:1
mc @ vendor~xpui.js:1
mc @ vendor~xpui.js:1
mc @ vendor~xpui.js:1
mc @ vendor~xpui.js:1
mc @ vendor~xpui.js:1
mc @ vendor~xpui.js:1
fc @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
_l @ vendor~xpui.js:1
il @ vendor~xpui.js:1
Bi @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
setTimeout
i @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
batch @ vendor~xpui.js:1
#a @ vendor~xpui.js:1
setData @ vendor~xpui.js:1
onSuccess @ vendor~xpui.js:1
m @ vendor~xpui.js:1
Promise.then
E @ vendor~xpui.js:1
start @ vendor~xpui.js:1
fetch @ vendor~xpui.js:1
#U @ vendor~xpui.js:1
onSubscribe @ vendor~xpui.js:1
subscribe @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Ta @ vendor~xpui.js:1
Qs @ vendor~xpui.js:1
El @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
b @ vendor~xpui.js:1
P @ vendor~xpui.js:1

spicetify-routes-library.js:1528 Uncaught (in promise) TypeError: result.filter is not a function
    at spicetify-routes-library.js:1528:33
```

**Comment by zszechuan** [comment]
I fixed it after cleaning out the library, everything works now
